# Generated by Django 5.1.3 on 2025-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='arms',
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='metric_type',
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='progressentry',
            name='value',
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='biceps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='calories_consumed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='workouts_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
